using System.Diagnostics;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;
using System.Windows.Shapes;

namespace PrinterRescue;
public sealed class P { public string Name{get;set;}=""; public string Type{get;set;}=""; public string Connection{get;set;}=""; public string Driver{get;set;}=""; public string Status{get;set;}=""; public string Port{get;set;}=""; }
public sealed class MainWindow:Window
{
 static readonly Brush Ink=B("#172033"), Muted=B("#5B6981"), Blue=B("#1E5BBF"), Navy=B("#174493"), Edge=B("#DBE1EB"), Bg=B("#F7F9FC"), Green=B("#168E51"), Amber=B("#D38910");
 readonly Grid root=new(); readonly DataGrid table=new(); readonly TextBlock count=new(),attention=new(),scanTime=new(),foot=new(),dn=new(),dt=new(),dc=new(),dd=new(),dp=new(),ds=new();
 static Brush B(string s)=>(Brush)new BrushConverter().ConvertFromString(s)!;
 public MainWindow(){Title="Printer Rescue";Width=1280;Height=800;MinWidth=1000;MinHeight=660;WindowStartupLocation=WindowStartupLocation.CenterScreen;FontFamily=new("Segoe UI");Background=Bg;Content=root;Build();Loaded+=async(_,_)=>await Scan();}
 Button Btn(string t,bool primary=false){var b=new Button{Content=t,Height=38,Padding=new(18,0,18,0),Margin=new(7,0,0,0),Background=primary?Blue:Brushes.White,Foreground=primary?Brushes.White:Ink,BorderBrush=primary?Blue:Edge,BorderThickness=new(1),FontWeight=FontWeights.SemiBold};return b;}
 FrameworkElement PrinterIcon(double n,Brush color,double opacity=1){var c=new Canvas{Width=n,Height=n,Opacity=opacity};c.Children.Add(new Rectangle{Width=n*.66,Height=n*.34,RadiusX=5,RadiusY=5,Fill=color,Margin=new(n*.17,n*.34,0,0)});c.Children.Add(new Rectangle{Width=n*.48,Height=n*.28,Fill=color,Margin=new(n*.26,n*.08,0,0)});c.Children.Add(new Rectangle{Width=n*.46,Height=n*.27,Fill=color,Margin=new(n*.27,n*.58,0,0)});return c;}
 void Build(){
  root.RowDefinitions.Add(new(){Height=new(102)});root.RowDefinitions.Add(new(){Height=new(46)});root.RowDefinitions.Add(new(){Height=new(1,GridUnitType.Star)});root.RowDefinitions.Add(new(){Height=new(34)});
  var h=new Grid{Background=Brushes.White};h.ColumnDefinitions.Add(new(){Width=new(1,GridUnitType.Star)});h.ColumnDefinitions.Add(new(){Width=GridLength.Auto});
  var brand=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center,Margin=new(26,0,0,0)};brand.Children.Add(PrinterIcon(54,Navy));var tx=new StackPanel{Margin=new(15,0,0,0),VerticalAlignment=VerticalAlignment.Center};tx.Children.Add(new TextBlock{Text="Printer Rescue",FontSize=29,FontWeight=FontWeights.Bold,Foreground=Ink});tx.Children.Add(new TextBlock{Text="Printer detection and recovery",FontSize=13,Foreground=Muted,Margin=new(0,4,0,0)});brand.Children.Add(tx);h.Children.Add(brand);
  var acts=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center,Margin=new(0,0,26,0)};var sb=Btn("Scan Printers",true);sb.Click+=async(_,_)=>await Scan();var sy=Btn("Sync Now");sy.Click+=(_,_)=>foot.Text="Catalogue sync is not enabled in this test build.";var st=Btn("Settings");st.Click+=(_,_)=>MessageBox.Show("Settings will be enabled later.","Printer Rescue");acts.Children.Add(sb);acts.Children.Add(sy);acts.Children.Add(st);Grid.SetColumn(acts,1);h.Children.Add(acts);root.Children.Add(h);
  var strip=new Grid{Background=B("#F0F5FD"),Margin=new(20,0,20,0)};for(int i=0;i<4;i++)strip.ColumnDefinitions.Add(new(){Width=new(1,GridUnitType.Star)});count.Text="0 printers detected";attention.Text="0 need attention";scanTime.Text="Last scan: not yet";S(strip,count,0);S(strip,attention,1);attention.Foreground=Amber;S(strip,scanTime,2);var cat=new TextBlock{Text="●  Local catalogue",Foreground=Green,FontWeight=FontWeights.SemiBold,VerticalAlignment=VerticalAlignment.Center,HorizontalAlignment=HorizontalAlignment.Right};Grid.SetColumn(cat,3);strip.Children.Add(cat);var sbdr=new Border{Background=B("#F0F5FD"),BorderBrush=Edge,BorderThickness=new(0,1,0,1),Child=strip};Grid.SetRow(sbdr,1);root.Children.Add(sbdr);
  var main=new Grid{Margin=new(20,16,20,16)};main.ColumnDefinitions.Add(new(){Width=new(56,GridUnitType.Star)});main.ColumnDefinitions.Add(new(){Width=new(12)});main.ColumnDefinitions.Add(new(){Width=new(44,GridUnitType.Star)});
  var lg=new Grid();lg.RowDefinitions.Add(new(){Height=new(48)});lg.RowDefinitions.Add(new(){Height=new(1,GridUnitType.Star)});lg.Children.Add(new TextBlock{Text="Printers on this PC",FontSize=16,FontWeight=FontWeights.SemiBold,Foreground=Ink,VerticalAlignment=VerticalAlignment.Center,Margin=new(16,0,0,0)});table.AutoGenerateColumns=false;table.HeadersVisibility=DataGridHeadersVisibility.Column;table.GridLinesVisibility=DataGridGridLinesVisibility.Horizontal;table.BorderThickness=new(0);table.RowHeight=62;table.ColumnHeaderHeight=38;table.IsReadOnly=true;table.SelectionMode=DataGridSelectionMode.Single;table.Background=Brushes.White;table.HorizontalGridLinesBrush=Edge;Col("Printer","Name",2.1);Col("Type","Type",1.1);Col("Connection","Connection",1.1);Col("Driver","Driver",1.7);Col("Status","Status",1);table.SelectionChanged+=(_,_)=>Select();Grid.SetRow(table,1);lg.Children.Add(table);var left=Panel(lg);main.Children.Add(left);
  var dg=new Grid{Margin=new(22)};for(int i=0;i<6;i++)dg.RowDefinitions.Add(new(){Height=i==5?new(1,GridUnitType.Star):GridLength.Auto});dg.Children.Add(new TextBlock{Text="Selected Printer",FontSize=16,FontWeight=FontWeights.SemiBold,Foreground=Ink});var hero=new Grid{Margin=new(0,18,0,18)};hero.ColumnDefinitions.Add(new(){Width=new(150)});hero.ColumnDefinitions.Add(new(){Width=new(1,GridUnitType.Star)});hero.Children.Add(PrinterIcon(105,B("#323B4B")));var hs=new StackPanel{VerticalAlignment=VerticalAlignment.Center};dn.Text="Select a printer";dn.FontSize=21;dn.FontWeight=FontWeights.Bold;dn.Foreground=Ink;dn.TextWrapping=TextWrapping.Wrap;ds.Foreground=Green;ds.FontWeight=FontWeights.SemiBold;ds.Margin=new(0,14,0,0);hs.Children.Add(dn);hs.Children.Add(ds);Grid.SetColumn(hs,1);hero.Children.Add(hs);Grid.SetRow(hero,1);dg.Children.Add(hero);var wm=PrinterIcon(200,Navy,.05);wm.HorizontalAlignment=HorizontalAlignment.Right;wm.VerticalAlignment=VerticalAlignment.Top;wm.Margin=new(0,40,-20,0);Grid.SetRowSpan(wm,6);dg.Children.Add(wm);
  var f=new Grid();f.ColumnDefinitions.Add(new(){Width=new(140)});f.ColumnDefinitions.Add(new(){Width=new(1,GridUnitType.Star)});for(int i=0;i<6;i++)f.RowDefinitions.Add(new(){Height=new(38)});F(f,"Type",dt,0);F(f,"Connection",dc,1);F(f,"Port",dp,2);F(f,"Driver",dd,3);var hw=new TextBlock{Text="Hardware ID",Foreground=Muted,VerticalAlignment=VerticalAlignment.Center};Grid.SetRow(hw,4);f.Children.Add(hw);var hwt=new TextBlock{Text="Collected in full build",Foreground=Muted,VerticalAlignment=VerticalAlignment.Center};Grid.SetRow(hwt,4);Grid.SetColumn(hwt,1);f.Children.Add(hwt);var rec=new TextBlock{Text="Recommended driver",Foreground=Muted,VerticalAlignment=VerticalAlignment.Center};Grid.SetRow(rec,5);f.Children.Add(rec);var r2=new TextBlock{Text="Not matched yet",Foreground=Ink,FontWeight=FontWeights.SemiBold,VerticalAlignment=VerticalAlignment.Center};Grid.SetRow(r2,5);Grid.SetColumn(r2,1);f.Children.Add(r2);Grid.SetRow(f,2);dg.Children.Add(f);var note=new TextBlock{Text="Driver matching and installation are intentionally disabled in this first test build.",Foreground=Muted,TextWrapping=TextWrapping.Wrap,Margin=new(0,14,0,18)};Grid.SetRow(note,3);dg.Children.Add(note);var ab=new Grid();ab.ColumnDefinitions.Add(new());ab.ColumnDefinitions.Add(new());var i1=Btn("Install Driver",true);i1.IsEnabled=false;i1.Margin=new(0,0,6,0);var i2=Btn("Test Print");i2.IsEnabled=false;i2.Margin=new(6,0,0,0);Grid.SetColumn(i2,1);ab.Children.Add(i1);ab.Children.Add(i2);Grid.SetRow(ab,4);dg.Children.Add(ab);var right=Panel(new ScrollViewer{Content=dg,VerticalScrollBarVisibility=ScrollBarVisibility.Auto});Grid.SetColumn(right,2);main.Children.Add(right);Grid.SetRow(main,2);root.Children.Add(main);
  foot.Text="Read-only test build. Printer Rescue will not install or change drivers.";foot.Foreground=Muted;foot.FontSize=12;foot.HorizontalAlignment=HorizontalAlignment.Center;foot.VerticalAlignment=VerticalAlignment.Center;Grid.SetRow(foot,3);root.Children.Add(foot);
 }
 Border Panel(UIElement c)=>new(){Background=Brushes.White,BorderBrush=Edge,BorderThickness=new(1),CornerRadius=new(9),Child=c};void S(Grid g,TextBlock t,int c){t.Foreground=Ink;t.FontWeight=FontWeights.SemiBold;t.VerticalAlignment=VerticalAlignment.Center;t.Margin=new(10,0,10,0);Grid.SetColumn(t,c);g.Children.Add(t);}void F(Grid g,string l,TextBlock v,int r){var x=new TextBlock{Text=l,Foreground=Muted,VerticalAlignment=VerticalAlignment.Center};v.Foreground=Ink;v.VerticalAlignment=VerticalAlignment.Center;v.TextTrimming=TextTrimming.CharacterEllipsis;Grid.SetRow(x,r);Grid.SetRow(v,r);Grid.SetColumn(v,1);g.Children.Add(x);g.Children.Add(v);}void Col(string h,string b,double w)=>table.Columns.Add(new DataGridTextColumn{Header=h,Binding=new Binding(b),Width=new DataGridLength(w,DataGridLengthUnitType.Star)});
 async Task Scan(){foot.Text="Scanning Windows for printers…";try{var a=await Task.Run(Detect);table.ItemsSource=a;count.Text=$"{a.Count} printer{(a.Count==1?"":"s")} detected";attention.Text=$"{a.Count(x=>x.Status!="Installed")} need attention";scanTime.Text=$"Last scan: {DateTime.Now:h:mm tt}";foot.Text=a.Count==0?"No printers detected. Connect a printer and scan again.":"Scan complete. Read-only test build.";if(a.Count>0)table.SelectedIndex=0;}catch(Exception e){foot.Text="Scan failed.";MessageBox.Show(e.Message,"Printer Rescue scan error",MessageBoxButton.OK,MessageBoxImage.Warning);}}
 List<P> Detect(){var q="Get-CimInstance Win32_Printer | Select Name,DriverName,PortName | ConvertTo-Json -Compress";var pi=new ProcessStartInfo("powershell.exe",$"-NoProfile -ExecutionPolicy Bypass -Command \"{q}\""){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true};using var p=Process.Start(pi)??throw new Exception("Could not start PowerShell.");var o=p.StandardOutput.ReadToEnd();var e=p.StandardError.ReadToEnd();p.WaitForExit();if(p.ExitCode!=0)throw new Exception(e);if(string.IsNullOrWhiteSpace(o))return new();using var j=JsonDocument.Parse(o);IEnumerable<JsonElement> es=j.RootElement.ValueKind==JsonValueKind.Array?j.RootElement.EnumerateArray():new[]{j.RootElement};var a=new List<P>();foreach(var z in es){string G(string name)=>z.TryGetProperty(name,out var v)&&v.ValueKind!=JsonValueKind.Null?v.ToString():"";var n=G("Name");var d=G("DriverName");var port=G("PortName");var con=port.StartsWith("USB",StringComparison.OrdinalIgnoreCase)?"USB":port.Contains('.')||port.StartsWith("IP_",StringComparison.OrdinalIgnoreCase)?"Network":"Local";a.Add(new(){Name=n,Type=T(n+" "+d),Connection=con,Driver=string.IsNullOrWhiteSpace(d)?"No driver installed":d,Status=string.IsNullOrWhiteSpace(d)?"Driver missing":"Installed",Port=port});}return a.OrderBy(x=>x.Name).ToList();}
 static string T(string s){if(s.Contains("receipt",StringComparison.OrdinalIgnoreCase)||s.Contains("thermal",StringComparison.OrdinalIgnoreCase)||s.Contains("xprinter",StringComparison.OrdinalIgnoreCase))return"Thermal Receipt";if(s.Contains("label",StringComparison.OrdinalIgnoreCase)||s.Contains("zebra",StringComparison.OrdinalIgnoreCase))return"Label / Barcode";if(s.Contains("inkjet",StringComparison.OrdinalIgnoreCase)||s.Contains("deskjet",StringComparison.OrdinalIgnoreCase)||s.Contains("ecotank",StringComparison.OrdinalIgnoreCase))return"Inkjet";if(s.Contains("laser",StringComparison.OrdinalIgnoreCase)||s.Contains("laserjet",StringComparison.OrdinalIgnoreCase)||s.Contains("HL-",StringComparison.OrdinalIgnoreCase))return"Laser";if(s.Contains("MFP",StringComparison.OrdinalIgnoreCase)||s.Contains("MF",StringComparison.OrdinalIgnoreCase))return"Multifunction";return"Printer";}
 void Select(){if(table.SelectedItem is not P p)return;dn.Text=p.Name;dt.Text=p.Type;dc.Text=p.Connection;dp.Text=p.Port;dd.Text=p.Driver;ds.Text=p.Status=="Installed"?"●  Installed":"●  Driver needs attention";ds.Foreground=p.Status=="Installed"?Green:Amber;}
}
public static class Program{[STAThread]public static void Main(){new Application().Run(new MainWindow());}}
