DEFAULT_SERVICES = [
    {
        "id": "teacher-recruitment",
        "label": "Teacher Recruitment",
        "icon": "teacher",
        "tag": "For Schools & Teachers",
        "title": "Connect the Right Teachers with the Right Schools",
        "summary": "A streamlined recruitment process that helps schools find qualified, culture-fit teachers.",
        "body": "Finding a great teacher is one of the most important decisions a school can make. RealMindX runs a streamlined recruitment process that takes the stress out of hiring, matching schools with qualified, passionate teachers who fit their vision and culture.\n\nWhether you are a school with a vacancy or a teacher looking for your next placement, we make the process fast, transparent, and effective.",
        "features": "Vetting and background checks for all candidates\nSubject and level-specific matching\nContract support and onboarding guidance\nOngoing placement follow-up",
        "primary_cta_label": "View Job Posts",
        "primary_cta_href": "/jobs",
        "secondary_cta_label": "Post a Vacancy",
        "secondary_cta_href": "/contact",
        "image_key": "recruitment",
        "badge": "Most Popular",
        "sort_order": 1,
        "status": "published",
    },
    {
        "id": "teacher-development",
        "label": "Teacher Development",
        "icon": "growth",
        "tag": "CPD Programs",
        "title": "Professional Growth for Every Educator",
        "summary": "Practical CPD programmes designed around real classroom challenges.",
        "body": "A school is only as strong as its teachers. Our customised training programs equip educators with the latest classroom strategies, subject expertise, and leadership skills, delivered online or face-to-face to fit your school's schedule.\n\nOur CPD workshops are built around real classroom challenges, not textbook theory.",
        "features": "Pedagogical strategy workshops\nClassroom management and behaviour support\nSubject-specific instructional coaching\nOnline and in-person delivery options\nCertificates of participation issued",
        "primary_cta_label": "Book a Programme",
        "primary_cta_href": "/contact",
        "secondary_cta_label": "",
        "secondary_cta_href": "",
        "image_key": "recruitment",
        "badge": "30+ Programmes",
        "sort_order": 2,
        "status": "published",
    },
    {
        "id": "school-structuring",
        "label": "School Structuring",
        "icon": "school",
        "tag": "Institutional Support",
        "title": "Building Schools That Actually Work",
        "summary": "Operational, cultural, and administrative support for stronger schools.",
        "body": "Whether you are starting a new school from scratch or fixing one that has lost its way, RealMindX offers comprehensive structuring services that cover everything from organisational design to school culture.\n\nWe work alongside leadership to build systems that outlast our involvement.",
        "features": "Organisational design and staff structure\nAdministrative systems and workflows\nPhysical infrastructure planning\nSchool culture and values development\nPolicy writing and handbook creation",
        "primary_cta_label": "Enquire Now",
        "primary_cta_href": "/contact",
        "secondary_cta_label": "",
        "secondary_cta_href": "",
        "image_key": "school",
        "badge": "",
        "sort_order": 3,
        "status": "published",
    },
    {
        "id": "bookshop",
        "label": "Bookshop",
        "icon": "book",
        "tag": "Wholesale & Retail",
        "title": "Quality Educational Materials, Delivered",
        "summary": "Textbooks, stationery, and learning materials for schools and families.",
        "body": "The RealMindX Bookshop stocks a wide range of textbooks, stationery, and learning materials at both wholesale and retail prices. We deliver across Accra and beyond, and offer pick-up options too.\n\nSchools and individuals are both welcome.",
        "features": "Textbooks for all grade levels\nStationery and classroom supplies\nWholesale pricing for bulk orders\nNationwide delivery\nIn-store pick-up available",
        "primary_cta_label": "Visit the Bookshop",
        "primary_cta_href": "/bookshop",
        "secondary_cta_label": "",
        "secondary_cta_href": "",
        "image_key": "bookshop",
        "badge": "",
        "sort_order": 4,
        "status": "published",
    },
    {
        "id": "tutoring",
        "label": "After-School Tutoring",
        "icon": "tutor",
        "tag": "Online & In-Person",
        "title": "Targeted Academic Support for Every Student",
        "summary": "Structured tutoring for learners who need extra academic support.",
        "body": "Our tutoring programmes give students the extra support they need, taught by qualified tutors in a structured, engaging environment. Sessions are tailored to the individual, not delivered as one-size-fits-all group lessons.\n\nWe cover all grade levels and major subjects.",
        "features": "One-on-one and small group sessions\nMathematics, Science, English and more\nHomework help and exam preparation\nProgress reports to parents\nOnline and in-person options",
        "primary_cta_label": "Book a Tutor",
        "primary_cta_href": "/contact",
        "secondary_cta_label": "",
        "secondary_cta_href": "",
        "image_key": "tutoring",
        "badge": "",
        "sort_order": 5,
        "status": "published",
    },
    {
        "id": "research",
        "label": "Research & Assignments",
        "icon": "research",
        "tag": "Academic Support",
        "title": "Expert Support for Researchers and Students",
        "summary": "Guidance for proposals, analysis, academic writing, and research structure.",
        "body": "From undergraduate assignments to doctoral research, our team provides structured academic support at every stage. We do not write work for students. We guide, coach, and support the process so the finished work is genuinely yours.\n\nAre you a researcher? Sign up to access our full support services, templates, and a dedicated advisor.",
        "features": "Research proposal development\nThesis and dissertation guidance\nData analysis and interpretation (SPSS, R, Excel)\nAcademic writing coaching\nPlagiarism checking and editing",
        "primary_cta_label": "Sign Up as a Researcher",
        "primary_cta_href": "https://forms.gle/1xsk9Km912UKQvEG9",
        "secondary_cta_label": "General Enquiry",
        "secondary_cta_href": "/contact",
        "image_key": "research",
        "badge": "",
        "sort_order": 6,
        "status": "published",
    },
    {
        "id": "secretarial",
        "label": "Secretarial Services",
        "icon": "secretarial",
        "tag": "Documentation & Admin",
        "title": "Professional Documentation Done Right",
        "summary": "Polished administrative, school, and business documentation support.",
        "body": "Our secretarial services handle the written and administrative work that schools, businesses, and individuals often struggle to find time for. Every document we produce is polished, accurate, and ready to use.",
        "features": "Business proposals and reports\nProofreading and editing\nPlagiarism checking and content originality\nDocument formatting and structuring\nSchool newsletters and official communications",
        "primary_cta_label": "Request a Service",
        "primary_cta_href": "/contact",
        "secondary_cta_label": "",
        "secondary_cta_href": "",
        "image_key": "secretarial",
        "badge": "",
        "sort_order": 7,
        "status": "published",
    },
    {
        "id": "special-education",
        "label": "Special Education",
        "icon": "special",
        "tag": "Inclusive Support",
        "title": "Every Child Deserves to Learn",
        "summary": "Inclusive education support for schools, families, and learners.",
        "body": "RealMindX is committed to inclusive education. We work with schools, parents, and specialists to develop proper support systems for students with special educational needs, ensuring no child is left behind.",
        "features": "Individualised Education Plans (IEPs)\nTeacher training on inclusive classroom practice\nLearning resource provision\nClassroom adaptation guidance\nParent and caregiver support sessions",
        "primary_cta_label": "Talk to Us",
        "primary_cta_href": "/contact",
        "secondary_cta_label": "",
        "secondary_cta_href": "",
        "image_key": "special",
        "badge": "Important Service",
        "sort_order": 8,
        "status": "published",
    },
    {
        "id": "consulting",
        "label": "Educational Consulting",
        "icon": "consulting",
        "tag": "Strategy & Policy",
        "title": "Expert Guidance for Better Educational Outcomes",
        "summary": "Strategy, policy, and improvement planning for education organisations.",
        "body": "Schools and education organisations often have the will to improve but are not sure where to start. Our consulting service provides expert, evidence-based guidance on policy, teaching effectiveness, and institutional strategy, translated into practical action plans.",
        "features": "School policy development\nData-driven insights and performance analysis\nStrategic planning and roadmap creation\nLeadership coaching and mentoring\nCurriculum design support",
        "primary_cta_label": "Schedule a Consultation",
        "primary_cta_href": "/contact",
        "secondary_cta_label": "",
        "secondary_cta_href": "",
        "image_key": "consulting",
        "badge": "",
        "sort_order": 9,
        "status": "published",
    },
    {
        "id": "extracurricular",
        "label": "Extracurricular Activities",
        "icon": "extra",
        "tag": "Beyond the Classroom",
        "title": "The Best Facilitators for What Matters Beyond Textbooks",
        "summary": "Reliable facilitators for co-curricular and practical enrichment activities.",
        "body": "A well-rounded education includes more than academics. RealMindX provides qualified facilitators for a wide range of extracurricular activities, available to schools and families both.",
        "features": "Swimming, Karate, and Cooking\nDrama, Music, and Dance\nArt, Painting, and Pottery\nFashion Design and UCMAS\nLanguages: French, Spanish, English and more",
        "primary_cta_label": "Explore Activities",
        "primary_cta_href": "/contact",
        "secondary_cta_label": "",
        "secondary_cta_href": "",
        "image_key": "tutoring",
        "badge": "",
        "sort_order": 10,
        "status": "published",
    },
    {
        "id": "home-schooling",
        "label": "Home Schooling Support",
        "icon": "home",
        "tag": "Personalised Learning",
        "title": "A Complete Home Education, Without the Stress",
        "summary": "Curriculum, lesson planning, tutors, and oversight for home education.",
        "body": "More parents in Ghana are choosing to educate their children at home. RealMindX supports that choice with structured guidance on curriculum selection, lesson planning, and progress tracking. For parents who want full management, we handle everything, from timetabling to teacher recruitment and academic oversight.",
        "features": "Curriculum selection and lesson planning\nFull home-schooling management available\nRecruitment of specialist home tutors\nPerformance monitoring and reporting\nFlexible, child-centred approach",
        "primary_cta_label": "Start Home Schooling",
        "primary_cta_href": "/contact",
        "secondary_cta_label": "",
        "secondary_cta_href": "",
        "image_key": "tutoring",
        "badge": "",
        "sort_order": 11,
        "status": "published",
    },
    {
        "id": "schoolms",
        "label": "SchoolMS",
        "icon": "schoolms",
        "tag": "School Management Platform",
        "title": "The School Management Platform Built for Ghana",
        "summary": "A complete cloud-based management system for Ghanaian schools.",
        "body": "SchoolMS is a complete, cloud-based school management system designed specifically for Ghanaian schools. It connects every role in the school, from the morning register to the end-of-term report card sitting in a parent's inbox before they even ask for it.\n\nEvery process that used to take hours now takes minutes.",
        "features": "Full school onboarded from a spreadsheet in minutes\nFees paid directly from parents' phones\nAttendance taken in two minutes, absent parents notified automatically\nAI-generated report card remarks built in\nSeparate portals for teachers, parents, and students",
        "primary_cta_label": "Explore SchoolMS",
        "primary_cta_href": "https://schoolms.realmindxgh.com",
        "secondary_cta_label": "Book a Demo",
        "secondary_cta_href": "/contact",
        "image_key": "school",
        "badge": "New Product",
        "sort_order": 12,
        "status": "published",
    },
]

DEFAULT_SITE_COPY = [
    {
        "id": "services_hero_title",
        "key": "services_hero_title",
        "label": "Services hero title",
        "value": "RealMindX Services",
        "area": "services",
        "status": "published",
    },
    {
        "id": "services_hero_body",
        "key": "services_hero_body",
        "label": "Services hero body",
        "value": "From teacher recruitment to school transformation, every RealMindX service is organised around one goal: making quality education easier to access, manage, and improve.",
        "area": "services",
        "status": "published",
    },
    {
        "id": "services_effective_note",
        "key": "services_effective_note",
        "label": "Services hero note",
        "value": "Built for schools, teachers, families, and learners across Ghana.",
        "area": "services",
        "status": "published",
    },
    {
        "id": "about_hero_body",
        "key": "about_hero_body",
        "label": "About hero body",
        "value": "A dynamic and innovative educational solutions provider dedicated to empowering schools, teachers, and students to achieve excellence.",
        "area": "about",
        "status": "published",
    },
    {
        "id": "about_who_title",
        "key": "about_who_title",
        "label": "About who-we-are title",
        "value": "A Company Built on a Simple Belief",
        "area": "about",
        "status": "published",
    },
    {
        "id": "about_who_body",
        "key": "about_who_body",
        "label": "About who-we-are body",
        "value": "RealMindX Education Limited is a registered Ghanaian company with a clear purpose: to make quality education available to every school, teacher, and learner who needs it.\n\nWe are not a tutoring centre. We are not a staffing agency. We are a comprehensive educational services provider, covering the full lifecycle of learning, from finding the right teacher to structuring the school they work in, from training that teacher to supporting the students in their class.\n\nThat breadth is deliberate. Education does not fail at one point. It fails across many interconnected ones, and fixing just one rarely changes outcomes. RealMindX exists to fix them together.",
        "area": "about",
        "status": "published",
    },
    {
        "id": "terms_body",
        "key": "terms_body",
        "label": "Terms body",
        "value": "The service terms for using RealMindX Education, the job portal, user portal, and bookshop. Users must provide accurate information, keep login credentials secure, and use the RealMindX platform for genuine education, recruitment, bookshop, and support purposes.",
        "area": "legal",
        "status": "published",
    },
    {
        "id": "privacy_body",
        "key": "privacy_body",
        "label": "Privacy body",
        "value": "How RealMindX handles account, application, contact, and bookshop information. We collect only what is needed to provide services, manage accounts, process enquiries, and keep the platform secure.",
        "area": "legal",
        "status": "published",
    },
    {
        "id": "home_impact_marquee",
        "key": "home_impact_marquee",
        "label": "Homepage impact marquee items",
        "value": "30+ CPD Programs Delivered\n200+ Research Projects\n100+ Teachers Recruited\nTrusted Across Ghana\nHolistic Learning for Every Mind",
        "area": "home",
        "status": "published",
    },
    {
        "id": "bookshop_pdp_delivery_info",
        "key": "bookshop_pdp_delivery_info",
        "label": "Bookshop product delivery information",
        "value": "Orders are dispatched within 24 hours and delivered nationwide within 48 hours. Greater Accra delivery from GHS 15; other regions calculated at checkout. Free pickup available at our Dome Pillar 2 shop.",
        "area": "bookshop",
        "status": "published",
    },
    {
        "id": "bookshop_pdp_return_policy",
        "key": "bookshop_pdp_return_policy",
        "label": "Bookshop product return policy",
        "value": "Unused items in original condition can be returned within 7 days for an exchange or store credit. Damaged or incorrect items are replaced free of charge - just reach out on WhatsApp.",
        "area": "bookshop",
        "status": "published",
    },
    {
        "id": "bookshop_terms_body",
        "key": "bookshop_terms_body",
        "label": "Bookshop terms body",
        "value": "These terms cover RealMindX Bookshop orders, enquiries, bulk requests, product availability, delivery, returns, and customer communication. Orders are confirmed only after staff review stock, payment, delivery destination, and any special instructions.",
        "area": "bookshop",
        "status": "published",
    },
    {
        "id": "bookshop_privacy_body",
        "key": "bookshop_privacy_body",
        "label": "Bookshop privacy body",
        "value": "RealMindX Bookshop collects customer names, contact details, order items, delivery preferences, payment references, and enquiry notes only to process orders, provide support, send confirmations, and improve the bookshop experience.",
        "area": "bookshop",
        "status": "published",
    },
]

DEFAULT_TESTIMONIALS = [
    {
        "id": "mr-james-bright-minds",
        "quote": "RealMindX transformed our school's teacher recruitment.",
        "name": "Mr. James",
        "role": "Principal, Bright Minds School",
        "sort_order": 1,
        "status": "published",
    },
    {
        "id": "mrs-clara-head-of-research",
        "quote": "Our research projects have improved greatly through RealMindX CPD programs.",
        "name": "Mrs. Clara",
        "role": "Head of Research",
        "sort_order": 2,
        "status": "published",
    },
    {
        "id": "mr-daniel-training-coordinator",
        "quote": "RealMindX made teacher development enjoyable.",
        "name": "Mr. Daniel",
        "role": "Training Coordinator",
        "sort_order": 3,
        "status": "published",
    },
    {
        "id": "mrs-grace-elite-high",
        "quote": "We recruited the best teachers easily through their platform.",
        "name": "Mrs. Grace",
        "role": "Principal, Elite High School",
        "sort_order": 4,
        "status": "published",
    },
]

DEFAULT_PARTNERS = [
    {"id": "bright-minds-school", "name": "Bright Minds School", "icon": "pBuilding", "image_file_id": None, "sort_order": 1, "status": "published"},
    {"id": "elite-high-school", "name": "Elite High School", "icon": "pBook", "image_file_id": None, "sort_order": 2, "status": "published"},
    {"id": "greater-accra-education", "name": "Greater Accra Education", "icon": "pStar", "image_file_id": None, "sort_order": 3, "status": "published"},
    {"id": "pillar-foundation", "name": "Pillar Foundation", "icon": "pColumn", "image_file_id": None, "sort_order": 4, "status": "published"},
    {"id": "open-books-initiative", "name": "Open Books Initiative", "icon": "pLeaf", "image_file_id": None, "sort_order": 5, "status": "published"},
    {"id": "volta-learning-trust", "name": "Volta Learning Trust", "icon": "pShield", "image_file_id": None, "sort_order": 6, "status": "published"},
]

DEFAULT_PEOPLE = [
    {
        "id": "founder-chief-executive",
        "name": "Team Member",
        "position": "Founder & CEO",
        "bio": "Leads RealMindX strategy, partnerships, and long-term education impact.",
        "initials": "FC",
        "image_file_id": None,
        "sort_order": 1,
        "status": "published",
    },
    {
        "id": "director-of-programmes",
        "name": "Team Member",
        "position": "Director of Programmes",
        "bio": "Coordinates learning programmes, school support, and service delivery standards.",
        "initials": "DP",
        "image_file_id": None,
        "sort_order": 2,
        "status": "published",
    },
    {
        "id": "head-of-teacher-placement",
        "name": "Team Member",
        "position": "Head of Teacher Placement",
        "bio": "Guides teacher vetting, school matching, onboarding, and placement follow-up.",
        "initials": "HT",
        "image_file_id": None,
        "sort_order": 3,
        "status": "published",
    },
    {
        "id": "research-consulting-lead",
        "name": "Team Member",
        "position": "Research & Consulting Lead",
        "bio": "Supports research, school improvement projects, documentation, and institutional consulting.",
        "initials": "RC",
        "image_file_id": None,
        "sort_order": 4,
        "status": "published",
    },
]

DEFAULT_HOME_HERO_SLIDES = [
    {"id": "school-structuring-hero", "label": "School Structuring", "image_key": "school", "image_file_id": None, "alt": "Students focused on classroom work at their desks", "sort_order": 1, "status": "published"},
    {"id": "teacher-recruitment-hero", "label": "Teacher Recruitment", "image_key": "recruitment", "image_file_id": None, "alt": "Students in a Ghanaian classroom focused on their work", "sort_order": 2, "status": "published"},
    {"id": "home-teaching-hero", "label": "Home Teaching", "image_key": "tutoring", "image_file_id": None, "alt": "A teacher guiding a young learner one-on-one at home", "sort_order": 3, "status": "published"},
    {"id": "special-education-hero", "label": "Special Education", "image_key": "special", "image_file_id": None, "alt": "A smiling student supported by inclusive education", "sort_order": 4, "status": "published"},
    {"id": "bookshop-hero", "label": "Bookshop", "image_key": "bookshop", "image_file_id": None, "alt": "Books and stationery on display at the RealMindX bookshop", "sort_order": 5, "status": "published"},
]

DEFAULT_DONATION_SLIDES = [
    {"id": "donation-learning-materials", "label": "Learning Materials", "image_key": "bookshop", "image_file_id": None, "alt": "Books and stationery for Ghanaian learners", "sort_order": 1, "status": "published"},
    {"id": "donation-teacher-development", "label": "Teacher Development", "image_key": "recruitment", "image_file_id": None, "alt": "Teacher development session with RealMindX educators", "sort_order": 2, "status": "published"},
    {"id": "donation-home-learning", "label": "Home Learning", "image_key": "tutoring", "image_file_id": None, "alt": "A child receiving learning support at home", "sort_order": 3, "status": "published"},
    {"id": "donation-school-systems", "label": "School Systems", "image_key": "school", "image_file_id": None, "alt": "School transformation and classroom support", "sort_order": 4, "status": "published"},
    {"id": "donation-inclusive-support", "label": "Inclusive Support", "image_key": "special", "image_file_id": None, "alt": "Inclusive education support for every learner", "sort_order": 5, "status": "published"},
]
